/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fileorganizer;

import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.sql.*;
import java.util.Vector;
import javax.swing.*;
import javax.swing.table.*;
import org.sqlite.JDBC;
/**
 *
 * @author KevinJiang
 */
public class FileOrganizer extends javax.swing.JFrame {

    /**
     * Creates new form FileOrganizer
     */
    public FileOrganizer() {
        super("收发文档管理器");
        
        connect();//连接数据库
        
        initComponents();
        jTable1.setComponentPopupMenu(createPopupMenu());//右键弹出菜单
        setLocationRelativeTo(null);//居中显示窗口
        DateChooser=new myDateChooser(jTextField5);
        showMetaData();//显示数据表头以测试数据库连接
        showDataInTable();//显示数据
    }
    
    //	弹出菜单
	private JPopupMenu createPopupMenu() {
        JPopupMenu popup = new JPopupMenu();
        
        JMenuItem myMenuItem1 = new JMenuItem("下一页");
        JMenuItem myMenuItem2 = new JMenuItem("上一页");
        JMenuItem myMenuItem3 = new JMenuItem("删除");
        
        popup.add(myMenuItem1);
        popup.add(myMenuItem2);
        
        myMenuItem1.addActionListener(new ActionListener() {			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				System.out.println("下一页");
			}
		});
        
        myMenuItem3.addActionListener(new ActionListener() {			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				System.out.println("删除");
			}
		});
 
        jTable1.addMouseListener(new PopupListener(popup));
        
        return popup;
    }
	
//	右键菜单
	private class PopupListener extends MouseAdapter {

        private JPopupMenu popup;

        PopupListener(JPopupMenu popupMenu) {
            popup = popupMenu;
        }

        public void mousePressed(MouseEvent e) {
            maybeShowPopup(e);
        }

         //限制只在表格内 
        public void mouseReleased(MouseEvent e) {
            if (jTable1.getSelectedRow() != -1) {
                maybeShowPopup(e);
            }
        }

        private void maybeShowPopup(MouseEvent e) {
            if (e.isPopupTrigger()) {
                popup.show(e.getComponent(), e.getX(), e.getY());
            }
        }
    }

    private void showDataInTable() {//显示数据
		//定义表格的数据模型
		DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                dtm.setRowCount(0);
		try {
                    rs = stat.executeQuery("Select * From test limit 20");//限制20个
			while (rs.next()) {
				Vector newRow = new Vector();
				int c = 1;
				while (c <= ColumnCount) {
					newRow.addElement(rs.getString(c));
					c++;
				}
				dtm.addRow(newRow);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void showMetaData() {//显示数据表头以测试数据库连接
    	ResultSetMetaData rsmd; //取得元数据
    	try {
    		rs = stat.executeQuery("Select * From test limit 1");//限制1个
			rsmd = rs.getMetaData();
			ColumnCount = rsmd.getColumnCount();
	    	for (int j = 1; j <= ColumnCount; j++) {
	    		System.out.println(rsmd.getColumnName(j));
	        }
    	} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
	}
        
        public boolean openFilebyDesktop(String path){  
  /**根据路径创建文件对象*/  
  File file = new File(path);  
  System.out.println(file.exists());  
  /**验证文件对象是否是文件*/  
  if(file.isFile()){  
   /**得到java.awt.Desktop对象 */  
   Desktop desktop = Desktop.getDesktop();  
   try {  
    /**打开文件*/  
    desktop.open(file);  
            } catch (Exception e) {  
             System.out.println(e);  
            }  
   return true;  
  }else{  
   return false;  
  }  
 }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int row,int col){
                return false;
            }
        };
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        FilePathButton = new javax.swing.JButton();
        FileOpenButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("数据库"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "收文号RecID", "来文单位Dept", "来文件号SendID", "标题Title", "收文日期RecDate", "文件链接Link"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("编辑器"));

        jLabel1.setText("收文号");

        jLabel2.setText("来文单位");

        jLabel3.setText("来文件号");

        jLabel4.setText("文件标题");

        jLabel5.setText("收文日期");

        jLabel6.setText("文件链接");

        jTextField1.setText("只有增加时才修改该值");

        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });

        jTextField6.setEditable(false);

        jButton3.setText("增加");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("保存");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("退出");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("搜索");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("删除");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("关于");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        FilePathButton.setText("指定文件路径");
        FilePathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilePathButtonActionPerformed(evt);
            }
        });

        FileOpenButton.setText("打开文件");
        FileOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileOpenButtonActionPerformed(evt);
            }
        });

        jButton7.setText("显示前50项");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel6))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jTextField3)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FilePathButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FileOpenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(58, 58, 58)
                        .addComponent(jButton7))
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton4))
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton6))
                            .addComponent(jButton3))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(FilePathButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jButton2)
                        .addComponent(jButton5)
                        .addComponent(FileOpenButton))
                    .addComponent(jButton7))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1156, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         String updateSql="insert into test VALUES("
                 + "'"+jTextField1.getText()
                 + "','"+jTextField2.getText()
                 + "','"+jTextField3.getText()
                 + "','"+jTextField4.getText()
                 + "','"+jTextField5.getText()
                 + "','"+jTextField6.getText()
                 +"')"; 
        try {
            stat.executeUpdate(updateSql);
            showDataInTable();
            //设置滚动条
            jScrollPane1.doLayout();    // 如果不是有改语句，滚动条会显示在中间
   
        JScrollBar jscrollBar = jScrollPane1.getVerticalScrollBar();
        if (jscrollBar != null)
        jscrollBar.setValue(jscrollBar.getMaximum()+1);
        
            System.out.println("已add");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "确认退出？", "退出",
				JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
			disconnect();
			System.exit(0);
		}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null,"功能还未实现");
        String[] head = {"RecID","Dept","SendID","Title","RecDate","Link"};
        String get1=(String)JOptionPane.showInputDialog(null,"请选择根据那一个属性搜索","搜索",JOptionPane.QUESTION_MESSAGE, null,head, head[0]);
        String get2=JOptionPane.showInputDialog(null,"请输入关键字");
        //System.out.println(get1+get2);
        //输出搜索结果
        //定义表格的数据模型
		DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                dtm.setRowCount(0);//get2="Select * From test where "+get1+" like '%"+get2+"%'";
		try {
                    rs = stat.executeQuery("Select * From test where "+get1+" like '%"+get2+"%'");
			while (rs.next()) {
				Vector newRow = new Vector();
				int c = 1;
				while (c <= ColumnCount) {
					newRow.addElement(rs.getString(c));
					c++;
				}
				dtm.addRow(newRow);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
         jButton1.setEnabled(true);
        jTextField1.setText((String)jTable1.getValueAt(row,0));
        jTextField2.setText((String)jTable1.getValueAt(row,1));
        jTextField3.setText((String)jTable1.getValueAt(row,2));
        jTextField4.setText((String)jTable1.getValueAt(row,3));
        jTextField5.setText((String)jTable1.getValueAt(row,4));
        jTextField6.setText((String)jTable1.getValueAt(row,5));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int row = jTable1.getSelectedRow();
         String updateSql="update test "// + "set Dept='sorry2"
                 + "set Dept='"+jTextField2.getText()
                 + "', SendID='"+jTextField3.getText()
                 + "', Title='"+jTextField4.getText()
                 + "', RecDate='"+jTextField5.getText()
                 + "', Link='"+jTextField6.getText()
                 + "' where RecID ='"+(String)jTable1.getValueAt(row,0)+"'"; 
        try {
            stat.executeUpdate(updateSql);
            showDataInTable();
            System.out.println("已save");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }    
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String updateSql="delete from test where RecID ='"+(String)jTable1.getValueAt(jTable1.getSelectedRow(),0)+"'";
        try {
            stat.executeUpdate(updateSql);
            showDataInTable();
            System.out.println("已delete");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }  
    }//GEN-LAST:event_jButton5ActionPerformed

    private void FilePathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilePathButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser (".");
        int result = file.showOpenDialog(null);
        String path=null;
        if(result == JFileChooser.APPROVE_OPTION){
        //获得你选择的文件绝对路径。并输出。当然，我们获得这个路径后还可以做很多的事。
            path = file.getSelectedFile().getAbsolutePath();
            System.out.println(path);
        }
        else{
            System.out.println("你已取消并关闭了窗口！");
        }
        jTextField6.setText(path);
    }//GEN-LAST:event_FilePathButtonActionPerformed

    private void FileOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileOpenButtonActionPerformed
        // TODO add your handling code here:
        if(!openFilebyDesktop(jTextField6.getText())){
            JOptionPane.showMessageDialog(null, "文件路径不对哦");
        }
    }//GEN-LAST:event_FileOpenButtonActionPerformed

    myDateChooser DateChooser;
    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        // TODO add your handling code here:
         DateChooser.showPanel();  
         //myDateChooser中的commit负责更新值
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "文件管理器 beta 1\n最后更新: 2013/5/22\nBy Manhua Jiang\nAll right reserved");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        showDataInTable();
    }//GEN-LAST:event_jButton7ActionPerformed

    
    Connection conn = null;
	Statement stat;
	ResultSet rs;
        int ColumnCount;//表头数
    
	// 连接数据库
	void connect() {
		try {
			// 连接SQLite的JDBC
			Class.forName("org.sqlite.JDBC");
			// 建立一个数据库名zieckey.db的连接，如果不存在就在当前目录下创建之
			conn = DriverManager.getConnection("jdbc:sqlite:test.db");
			stat = conn.createStatement();
                       // JOptionPane.showMessageDialog(null,"已连接数据库");
		} catch (Exception e) {
			e.printStackTrace();
		}
		if( null == conn){
			JOptionPane.showMessageDialog(null,"连接数据库失败");
			System.exit(1);
		}
			
	}

	// 断开连接
	void disconnect() {
		try {
			// rs.close();
			conn.close();// 结束数据库的连接
		} catch (SQLException e) {
			e.printStackTrace();
		}
		//JOptionPane.showMessageDialog(null,	"已断开数据库");
	}

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileOrganizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileOrganizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileOrganizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileOrganizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileOrganizer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FileOpenButton;
    private javax.swing.JButton FilePathButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
